export enum DECODED_EVENT_CATEGORY {
    NFT = "NFT Transaction",
    LENDING = "Lending",
    SAFE = "SAFE",
    DEX = "DEX",
    TOKEN = "Token",
    SYNTHTIC = "Synthtic",
    MARGIN = "Margin",
    VAULT = "Vault",
    METAVERSE = "Metaverse",
    SWAP = "Swap",
    DEFI = "DeFi",
    BRIDGE = "Bridge",
    GAMING = "Gaming",
    SOCIAL = "Social",
    STAKING = "Staking",
    PERPETUAL = "Perpetual",
    OTHERS = "Others",
}

export enum DECODED_ACTION {
    SWAPPED = "Swapped",
    MULTISIG_ACTION = "MultiSig",
    APPROVAL = "Approval",
    TRANSFERRED = "Transferred",
    TRANSFERRED_SHARE = "Transferred Shares",
    NATIVE_TRANSFER = "Native Token Transfer",
    RECEIVED_BRIDGE = "Received Bridge",
    ACCOUNT_ABSTRACTION = "Account Abstraction Transaction",
    SALE = "Sale",
    MINT = "Mint",
    BURN = "Burn",
    COLLECT = "Collect",
    WITHDRAW = "Withdraw",
    WITHDRAW_COMPLETED = "Withdraw Completed",
    WITHDRAW_QUEUED = "Withdraw Queued",
    WITHDRAW_REQUEST = "Withdraw Requested",
    DEPOSIT = "Deposit",
    SUPPLY = "Supply",
    ADD_LIQUIDITY = "Add Liquidity",
    REMOVE_LIQUIDITY = "Remove Liquidity",
    UPDATE = "Update",
    FLASHLOAN = "Flashloan",
    REPAY = "Repay",
    BORROW = "Borrow",
    LIQUIDATE = "Liquidate",
    CLAIM_REWARDS = "Claim Rewards",
    GAME_ACTION = "Game Action",
    CREATE = "Create Pool",
    INIT_ROUTER = "Init Router",
    ADD_ROUTER = "Add Router",
    REMOVE_ROUTER = "Remove Router",
}
